app:
  port: 28080
  grpc_port: 50051

database:
  host: postgres-user
  port: 5432
  user: admin
  password: admin
  name: user

redis:
  host: redis
  port: 6379
  password: admin

secret:
  jwt_secret: secret301

vault:
  host: http://vault:8200
  token: fcproject
  path: userfc

tracing:
  endpoint: jaeger:4318
  service_name: userfc
  enabled: true
